declare global {interface Window {ScrollCraft?:{mount:()=>unknown}}}
window.ScrollCraft?.mount();
const resolution=document.querySelector('.resolution');
if(resolution){const map=document.createElement('div');map.className='work-map';map.setAttribute('aria-label','An illustrative map of interests: play, tools, and learning');for(const [i,label] of ['Play','Tools','Learning'].entries()){if(i){const connector=document.createElement('i');connector.textContent='↔';connector.setAttribute('aria-hidden','true');map.append(connector);}const node=document.createElement('span');node.textContent=label;map.append(node);}resolution.insertBefore(map,resolution.querySelector('p'));}
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}}),{threshold:.1});document.querySelectorAll('.award h2,.resolution p').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el);});}
const folio=document.querySelector<HTMLElement>('.folio');
const captions:Record<string,string>={start:'A few squares. A starting point.',practice:'Building around shared goals.',tools:'Connections make tools useful.',win:'A shared milestone.',create:'Different projects. Connected interests.',about:'And room for what comes next.'};
const sections=[...document.querySelectorAll<HTMLElement>('.chapter')];
const update=()=>{let active=sections[0]?.id;for(const section of sections){if(section.getBoundingClientRect().top<innerHeight*.45)active=section.id;}if(!active)return;if(folio)folio.dataset.state=active;document.querySelectorAll('[data-chapter-link]').forEach(link=>{if(link.getAttribute('data-chapter-link')===active)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');});const caption=document.querySelector('#grid-caption');if(caption)caption.textContent=captions[active];};
let queued=false;addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(()=>{update();queued=false;});}},{passive:true});update();
const grid=document.querySelector('#paint-grid');let drawing=false;
const paint=(target:EventTarget|null)=>{if(target instanceof HTMLButtonElement&&grid?.contains(target))target.setAttribute('aria-pressed','true');};
grid?.addEventListener('pointerdown',event=>{if((event as PointerEvent).button!==0)return;drawing=true;paint(event.target);});grid?.addEventListener('pointerover',event=>{if(drawing)paint(event.target);});grid?.addEventListener('pointermove',event=>{const pointer=event as PointerEvent;if(drawing)paint(document.elementFromPoint(pointer.clientX,pointer.clientY));});addEventListener('pointerup',()=>drawing=false);addEventListener('pointercancel',()=>drawing=false);addEventListener('blur',()=>drawing=false);grid?.addEventListener('click',event=>paint(event.target));document.querySelector('#clear-grid')?.addEventListener('click',()=>grid?.querySelectorAll('button').forEach(button=>button.setAttribute('aria-pressed','false')));
